import json, os
import pandas as pd, numpy as np
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm
import nbformat as nbf
import matplotlib
matplotlib.use('Agg')
from nbconvert.preprocessors import ExecutePreprocessor
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT

ROOT=os.path.dirname(os.path.abspath(__file__))
DATA=os.path.join(ROOT,'california_housing.csv')
df=pd.read_csv(DATA)
X=df.drop(columns='median_house_value'); y=df['median_house_value']
num=X.select_dtypes(include=np.number).columns.tolist(); cat=X.select_dtypes(exclude=np.number).columns.tolist()
pre=ColumnTransformer([('num',Pipeline([('imp',SimpleImputer(strategy='median')),('scale',StandardScaler())]),num),('cat',Pipeline([('imp',SimpleImputer(strategy='most_frequent')),('oh',OneHotEncoder(handle_unknown='ignore',sparse_output=False,drop='first'))]),cat)])
model=Pipeline([('preprocessor',pre),('regressor',LinearRegression())])
Xtr,Xte,ytr,yte=train_test_split(X,y,test_size=.2,random_state=42)
model.fit(Xtr,ytr); pred=np.dot(model.named_steps['preprocessor'].transform(Xte), model.named_steps['regressor'].coef_)+model.named_steps['regressor'].intercept_
mse=mean_squared_error(yte,pred); mae=mean_absolute_error(yte,pred); r2=r2_score(yte,pred)
features=model.named_steps['preprocessor'].get_feature_names_out(); coefs=model.named_steps['regressor'].coef_.copy()
coefs[:len(num)] = coefs[:len(num)] / model.named_steps['preprocessor'].named_transformers_['num'].named_steps['scale'].scale_
coef=pd.DataFrame({'feature':features,'coefficient':coefs}).sort_values('coefficient',key=abs,ascending=False)
vif_input=sm.add_constant(Xtr[num].fillna(Xtr[num].median()), has_constant='add')
vif_df=pd.DataFrame({'feature':num,'VIF':[variance_inflation_factor(vif_input.values,i+1) for i in range(len(num))]})

def md(s): return nbf.v4.new_markdown_cell(s)
def code(s): return nbf.v4.new_code_cell(s)
cells=[md('# Laboratory Assignment №2\n## Task 1 — House Price Prediction using Multiple Linear Regression\n**Students:** Kazbek Assanbek, Yerserik  \n**Group:** IT2-2302\n\nThis notebook predicts the median house value from district-level housing characteristics. It is designed to run from top to bottom using the included `california_housing.csv` file.'),
md('## 1. Problem description and theory\nThe task is supervised regression: each row describes one California census district and the target is its median house value in US dollars. The multiple linear regression model is\n\n$$\\hat{y}=\\beta_0+\\beta_1x_1+\\beta_2x_2+\\cdots+\\beta_px_p.$$\n\nHere, $\\hat{y}$ is the predicted price, $\\beta_0$ is the intercept, $\\beta_j$ is a coefficient, and $x_j$ is a feature. In matrix/probabilistic form, $y=X\\beta+\\varepsilon$, with the classical Gaussian interpretation $\\varepsilon\\sim N(0,\\sigma^2)$. The model assumes approximate linearity, independent errors, reasonably constant error variance, and no problematic multicollinearity. Normal residuals are mainly needed for classical inference, not merely for prediction.\n\nTraining minimizes $MSE=\\frac1n\\sum_i(y_i-\\hat y_i)^2$; squaring gives larger errors a larger penalty.'),
md('## 2. Imports and data loading'), code("""import numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.impute import SimpleImputer\nfrom sklearn.preprocessing import OneHotEncoder\nfrom sklearn.linear_model import LinearRegression\nfrom sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score\nfrom statsmodels.stats.outliers_influence import variance_inflation_factor\nimport statsmodels.api as sm\n\nRANDOM_STATE = 42\ndf = pd.read_csv('california_housing.csv')\ndf.head()"""),
md('## 3. Initial inspection\nDataset source: **California Housing Prices — Kaggle — Cam Nugent** ([dataset page](https://www.kaggle.com/datasets/camnugent/california-housing-prices)). This is the CSV `housing.csv` version, not sklearn\'s `fetch_california_housing` object. One row represents a census district. The target is `median_house_value`; the other columns describe location, age, rooms, population, income, and ocean proximity.'),
code("""print('Shape:', df.shape)\nprint('Columns:', df.columns.tolist())\nprint('\\nData types:')\nprint(df.dtypes)\nprint('\\nMissing values:')\nprint(df.isna().sum())\nprint('\\nDescriptive statistics:')\ndf.describe(include='all').T"""),
md('## 4. Preprocessing and exploratory analysis\nThere are numerical and categorical features. Missing numerical values are replaced by the training median, while the categorical value is imputed by its most frequent category. `OneHotEncoder` converts `ocean_proximity` into indicator columns. These operations are inside a pipeline, so they are learned only from the training set and do not leak test information.'),
code("""X = df.drop(columns='median_house_value')\ny = df['median_house_value']\nnumeric_features = X.select_dtypes(include=np.number).columns.tolist()\ncategorical_features = X.select_dtypes(exclude=np.number).columns.tolist()\nprint('Numerical features:', numeric_features)\nprint('Categorical features:', categorical_features)\n\nfig, ax = plt.subplots(1, 2, figsize=(12, 4))\nax[0].hist(y, bins=40, edgecolor='white')\nax[0].set(title='Distribution of median house value', xlabel='Price (USD)', ylabel='District count')\nax[1].scatter(df['median_income'], y, s=4, alpha=.25)\nax[1].set(title='Income and target relationship', xlabel='Median income (tens of thousands USD)', ylabel='Price (USD)')\nplt.tight_layout(); plt.savefig('eda.png', dpi=160); plt.show()"""),
md('## 5. Feature/target separation and train/test split'), code("""X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=RANDOM_STATE)\nprint('Training rows:', len(X_train), '| Test rows:', len(X_test))"""),
md('## 6. Model initialization and fitting'), code("""numeric_pipe = Pipeline([('imputer', SimpleImputer(strategy='median'))])\ncategorical_pipe = Pipeline([('imputer', SimpleImputer(strategy='most_frequent')), ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))])\npreprocessor = ColumnTransformer([('numeric', numeric_pipe, numeric_features), ('categorical', categorical_pipe, categorical_features)])\nmodel = Pipeline([('preprocessor', preprocessor), ('regressor', LinearRegression())])\nmodel.fit(X_train, y_train)\ny_pred = model.predict(X_test)\nprint('LinearRegression fitted successfully.')"""),
md('## 7. Evaluation'), code("""mse = mean_squared_error(y_test, y_pred)\nmae = mean_absolute_error(y_test, y_pred)\nr2 = r2_score(y_test, y_pred)\nresults = pd.DataFrame({'Metric':['MSE','MAE','R²'], 'Value':[mse,mae,r2]})\nresults"""),
md('MSE is the average squared prediction error and is expressed in squared dollars. MAE is the average absolute error in dollars, so it is easier to interpret. R² is the proportion of target variation explained by the model on the test set.'),
md('## 8. Regression coefficients'), code("""feature_names = model.named_steps['preprocessor'].get_feature_names_out()\ncoefficients = pd.DataFrame({'feature':feature_names, 'coefficient':model.named_steps['regressor'].coef_})\ncoefficients['absolute'] = coefficients['coefficient'].abs()\ncoefficients.sort_values('absolute', ascending=False).drop(columns='absolute').head(15)"""),
md('A coefficient is the expected change in predicted target for a one-unit increase in that feature, holding the other inputs fixed. It is an association in this predictive model, not automatically a causal effect. One-hot coefficients are relative to the omitted reference category.'),
md('## 9. Multicollinearity analysis'), code("""vif_input = sm.add_constant(X_train[numeric_features].fillna(X_train[numeric_features].median()), has_constant='add')\nvif_table = pd.DataFrame({'feature':numeric_features, 'VIF':[variance_inflation_factor(vif_input.values, i + 1) for i in range(len(numeric_features))]})\nvif_table.sort_values('VIF', ascending=False)"""),
md('Multicollinearity occurs when predictors contain overlapping information. It can make individual coefficients unstable and harder to interpret, although predictions may still be useful. VIF is a diagnostic; values around 5 or 10 are sometimes used as rules of thumb, not universal laws. The categorical indicators are omitted from this compact VIF table because the numerical predictors are the clearest diagnostic here.'),
md('## 10. Visualizations'), code("""fig, ax = plt.subplots(figsize=(6, 5))\nax.scatter(y_test, y_pred, s=8, alpha=.3)\nlims=[min(y_test.min(),y_pred.min()),max(y_test.max(),y_pred.max())]\nax.plot(lims,lims,'r--',label='Perfect prediction')\nax.set(title='Actual vs predicted house values', xlabel='Actual value (USD)', ylabel='Predicted value (USD)'); ax.legend(); plt.tight_layout(); plt.savefig('actual_vs_predicted.png', dpi=160); plt.show()\n\nresiduals=y_test-y_pred\nfig,ax=plt.subplots(figsize=(7,4)); ax.scatter(y_pred,residuals,s=8,alpha=.3); ax.axhline(0,color='r',ls='--')\nax.set(title='Residuals vs predicted values',xlabel='Predicted value (USD)',ylabel='Residual (actual − predicted)'); plt.tight_layout(); plt.savefig('residuals.png', dpi=160); plt.show()\n\ntop=coefficients.sort_values('absolute').tail(15)\nfig,ax=plt.subplots(figsize=(8,5)); ax.barh(top['feature'],top['coefficient']); ax.axvline(0,color='black',lw=.7)\nax.set(title='Largest regression coefficients',xlabel='Coefficient (USD per feature unit)',ylabel='Encoded feature'); plt.tight_layout(); plt.savefig('coefficients.png', dpi=160); plt.show()"""),
md('## 11. Conclusion\nThe required multiple linear regression model was trained with a reproducible 80/20 split. The test metrics quantify predictive accuracy, while the coefficient and VIF tables show how interpretation is affected by feature scale and overlapping predictors. The model is a useful baseline, but nonlinear relationships, capped target values, and district-level sampling limit how literally coefficients should be interpreted.')]
for c in cells:
    c['source']=c['source'].replace("OneHotEncoder(handle_unknown='ignore', sparse_output=False)", "OneHotEncoder(handle_unknown='ignore', sparse_output=False, drop='first')")
    c['source']=c['source'].replace("from sklearn.preprocessing import OneHotEncoder", "from sklearn.preprocessing import OneHotEncoder, StandardScaler")
    c['source']=c['source'].replace("numeric_pipe = Pipeline([('imputer', SimpleImputer(strategy='median'))])", "numeric_pipe = Pipeline([('imputer', SimpleImputer(strategy='median')), ('scale', StandardScaler())])")
    c['source']=c['source'].replace("OneHotEncoder converts `ocean_proximity` into indicator columns", "StandardScaler standardizes numerical features, and OneHotEncoder(drop='first') converts `ocean_proximity` into reference-category indicators")
    c['source']=c['source'].replace("vif_input = X_train[numeric_features].fillna(X_train[numeric_features].median())\\nvif_table = pd.DataFrame({'feature':numeric_features, 'VIF':[variance_inflation_factor(vif_input.values, i) for i in range(len(numeric_features))]})", "vif_input = sm.add_constant(X_train[numeric_features].fillna(X_train[numeric_features].median()), has_constant='add')\\nvif_table = pd.DataFrame({'feature':numeric_features, 'VIF':[variance_inflation_factor(vif_input.values, i + 1) for i in range(len(numeric_features))]})")
    c['source']=c['source'].replace("One-hot coefficients are relative to the omitted reference category.", "One-hot coefficients are relative to the omitted reference category `NEAR BAY`.")
    c['source']=c['source'].replace("feature_names = model.named_steps['preprocessor'].get_feature_names_out()", "feature_names = model.named_steps['preprocessor'].get_feature_names_out()\nreference_category = model.named_steps['preprocessor'].named_transformers_['categorical'].named_steps['onehot'].categories_[0][0]\nprint('Dropped/reference ocean_proximity category:', reference_category)")
    c['source']=c['source'].replace("coefficients = pd.DataFrame({'feature':feature_names, 'coefficient':model.named_steps['regressor'].coef_})", "raw_coefficients = model.named_steps['regressor'].coef_.copy()\nraw_coefficients[:len(numeric_features)] = raw_coefficients[:len(numeric_features)] / model.named_steps['preprocessor'].named_transformers_['numeric'].named_steps['scale'].scale_\ncoefficients = pd.DataFrame({'feature':feature_names, 'coefficient':raw_coefficients})")
    c['source']=c['source'].replace("model.fit(X_train, y_train)\ny_pred = model.predict(X_test)", "with np.errstate(divide='ignore', over='ignore', invalid='ignore'):\n    model.fit(X_train, y_train)\n    y_pred = model.predict(X_test)")
    c['source']=c['source'].replace("The model is a useful baseline, but nonlinear relationships, capped target values, and district-level sampling limit how literally coefficients should be interpreted.", "The model is a useful baseline, but nonlinear relationships, capped target values, and district-level sampling limit how literally coefficients should be interpreted. Ordinary Linear Regression has an unbounded output, so it may produce unrealistic negative house-price predictions for some observations.")
    c['source']=c['source'].replace('no problematic multicollinearity', 'classical regression prefers low multicollinearity, but the VIF analysis shows this condition is not fully satisfied in this dataset')
    c['source']=c['source'].replace("plt.tight_layout(); plt.savefig('actual_vs_predicted.png', dpi=160); plt.show()", "plt.tight_layout(); plt.savefig('actual_vs_predicted.png', dpi=160); plt.show()\nprint('The vertical concentration near actual = $500,001 is caused by multiple observations sharing the dataset maximum target; points near the diagonal have smaller errors.')\nprint('Minimum predicted value:', y_pred.min())")
    c['source']=c['source'].replace("plt.tight_layout(); plt.savefig('residuals.png', dpi=160); plt.show()", "plt.tight_layout(); plt.savefig('residuals.png', dpi=160); plt.show()\nprint(\"The diagonal residual boundary is caused by the dataset's capped maximum target value of $500,001, not by a plotting error.\")")
    c['source']=c['source'].replace("print('Dropped/reference ocean_proximity category:', reference_category)", "print('Dropped/reference ocean_proximity category:', reference_category)\nprint('Maximum actual target:', y.max(), '| Observations at cap:', (y == y.max()).sum())")
nb=nbf.v4.new_notebook(); nb['cells']=cells; nb['metadata']={'kernelspec':{'display_name':'Python 3','language':'python','name':'python3'},'language_info':{'name':'python','version':'3'}}
nbpath=os.path.join(ROOT,'IT2-2302_Assanbek_Yerserik.ipynb'); nbf.write(nb,nbpath)
ep=ExecutePreprocessor(timeout=120,kernel_name='python3'); ep.preprocess(nb,{'metadata':{'path':ROOT}}); nbf.write(nb,nbpath)

doc=Document(); sec=doc.sections[0]; sec.top_margin=Inches(.75); sec.bottom_margin=Inches(.75); sec.left_margin=Inches(.9); sec.right_margin=Inches(.9)
styles=doc.styles; styles['Normal'].font.name='Arial'; styles['Normal'].font.size=Pt(10)
p=doc.add_paragraph(); p.alignment=WD_ALIGN_PARAGRAPH.CENTER; r=p.add_run('LABORATORY ASSIGNMENT №2\nTASK 1: HOUSE PRICE PREDICTION'); r.bold=True; r.font.size=Pt(16)
p=doc.add_paragraph(); p.alignment=WD_ALIGN_PARAGRAPH.CENTER; p.add_run('Students: Kazbek Assanbek, Yerserik\nGroup: IT2-2302').italic=True
def H(t,l=1): doc.add_heading(t,level=l)
def P(t): doc.add_paragraph(t)
H('1. Problem Description'); P('The goal is to predict a continuous house-price target from district-level housing characteristics. Multiple Linear Regression is required because it estimates the target from several predictors simultaneously.')
H('2. Input and Output'); P('Inputs are longitude, latitude, housing median age, total rooms, total bedrooms, population, households, median income, and ocean proximity. The output is median_house_value, the median house value for a census district, measured in US dollars.')
H('3. Dataset'); P(f'Source: California Housing Prices — Kaggle — Cam Nugent (https://www.kaggle.com/datasets/camnugent/california-housing-prices). The included file is the CSV housing.csv version, not sklearn\'s fetch_california_housing object. Each row represents one California census district. The dataset contains {df.shape[0]:,} rows and {df.shape[1]} columns (9 predictors plus target). Missing values: {int(df.isna().sum().sum())}. Numerical features were median-imputed in the training pipeline; ocean_proximity was one-hot encoded. Keeping the CSV with the submission makes the experiment reproducible.')
P('The target mean is $%.2f and the target standard deviation is $%.2f. Median income has a mean of %.2f, while median house value ranges from $%.0f to $%.0f.'%(y.mean(),y.std(),df.median_income.mean(),y.min(),y.max()))
H('4. Multiple Linear Regression'); P('The model fits one linear equation with an intercept and one coefficient for each transformed feature. Categorical ocean-proximity values become binary indicator variables with drop-first encoding. The dropped/reference category is <1H OCEAN; retained dummy coefficients are conditional differences relative to it. The fitted model was sklearn.linear_model.LinearRegression.')
H('5. Mathematical Formula'); P('ŷ = β₀ + β₁x₁ + β₂x₂ + ... + βₚxₚ. Here ŷ is predicted price, β₀ is the intercept, βⱼ is a regression coefficient, and xⱼ is an input feature.')
H('6. Probabilistic Intuition and Assumptions'); P('The model can be written y = Xβ + ε. Under the classical Gaussian interpretation, ε ~ N(0, σ²). We assume approximate linearity, independent errors, approximately constant error variance, and no severe multicollinearity. Normal residuals are mainly relevant to statistical inference; prediction does not require perfect normality.')
H('7. Loss Function — Mean Squared Error'); P('MSE = (1/n) Σ(yᵢ − ŷᵢ)². Training minimizes this loss. Squaring means that large errors receive disproportionately larger penalties.')
H('8. Regression Coefficients'); P('A numeric coefficient estimates the expected change in model prediction for a one-unit increase in that feature, holding other inputs fixed. Ocean-proximity dummy coefficients are conditional differences relative to the omitted reference category <1H OCEAN. These are model associations, not proof of causation. The rare ISLAND coefficient should be interpreted cautiously because its estimate may be less stable.')
t=doc.add_table(rows=1, cols=2); t.alignment=WD_TABLE_ALIGNMENT.CENTER; t.style='Light Shading Accent 1'; t.rows[0].cells[0].text='Feature'; t.rows[0].cells[1].text='Coefficient'
for _,row in coef.head(8).iterrows(): c=t.add_row().cells; c[0].text=row.feature; c[1].text=f"{row.coefficient:,.2f}"
P('The strongest absolute coefficients include '+', '.join(f'{r.feature} ({r.coefficient:,.0f})' for _,r in coef.head(3).iterrows())+'. These values are conditional model estimates and are not causal claims.')
H('9. Multicollinearity'); P('Multicollinearity means that predictors overlap in the information they provide. The classical regression framework prefers low multicollinearity, but this VIF analysis shows substantial multicollinearity among several predictors, especially housing-count variables. It can affect coefficient stability and interpretability, while predictive use is not automatically invalidated. VIF is used as a diagnostic; 5 or 10 are rules of thumb, not strict universal cutoffs.')
t=doc.add_table(rows=1, cols=2); t.style='Light Shading Accent 1'; t.rows[0].cells[0].text='Numerical feature'; t.rows[0].cells[1].text='VIF'
for _,row in vif_df.sort_values('VIF',ascending=False).iterrows(): c=t.add_row().cells; c[0].text=row.feature; c[1].text=f'{row.VIF:.2f}'
H('10. Implementation Summary'); P('The data were split into 80% training and 20% testing with random_state=42. Median imputation, StandardScaler for numerical features, and drop-first one-hot encoding were placed inside a scikit-learn Pipeline/ColumnTransformer to prevent test-set leakage. The model was fitted on training data and evaluated once on the held-out test set.')
H('11. Evaluation Metrics'); P('MSE is the mean squared error, MAE is the average absolute dollar error, and R² is the fraction of test-target variance explained by the model.')
t=doc.add_table(rows=1, cols=2); t.style='Light Shading Accent 1'; t.rows[0].cells[0].text='Metric'; t.rows[0].cells[1].text='Test result'
for a,b in [('MSE',f'{mse:,.2f}'),('MAE',f'{mae:,.2f}'),('R²',f'{r2:.4f}')]: c=t.add_row().cells; c[0].text=a;c[1].text=b
H('12. Actual Experimental Results'); P(f'On the 4,128-row test set, the model achieved an MAE of ${mae:,.2f} USD; a typical absolute prediction error is therefore about this size. R²={r2:.4f} indicates that the linear model explains approximately {r2*100:.1f}% of held-out target variation. The MSE is {mse:,.2f} USD². The capped target and nonlinear geography/income effects are important limitations. The maximum recorded target is $500,001, shared by {(y == y.max()).sum():,} observations. Ordinary Linear Regression has an unbounded output; the minimum prediction was ${pred.min():,.2f}, so some predictions can be unrealistic negative prices.')
H('13. Short Conclusion'); P('Multiple Linear Regression provided a clear and reproducible baseline for house-price prediction. The pipeline handled the mixed feature types correctly, and the actual test metrics show useful predictive power. Residuals and VIF diagnostics indicate that the model should be used as a baseline rather than as a causal pricing formula.')
doc.save(os.path.join(ROOT,'Assanbek_Yerserik.docx'))
print(json.dumps({'rows':len(df),'cols':len(df.columns),'mse':mse,'mae':mae,'r2':r2,'top_coefficients':coef.head(5).to_dict('records'),'vif':vif_df.to_dict('records')}))
